### PR TITLE
Update ruby and rspec

### PR DESCRIPTION
**Pull request by jnwaletzko**
Description and Impact
----------------------
> Updates Ruby to 2.2.0

Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?

Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.

URLs
----
> Links to bug tickets or user stories.

QA Plan
-------
> Fill in scenarios below in checklist format.
> Consider Regression scenarios (did we break something else related to this change) in addition to Happy Path (testing the new feature directly).
> Evaluate the risk level and label accordingly and ensure the QA Plan matches the risk level!

### CODE REVIEW

**Comment by jphenow** [comment]
Nice.

**Comment by jerickson** [comment]
`A wild Phenow appears...`

I thought it was safe because the previous run succeeded.   `Bundler!!!!!!!!!!!!!!!!!!!!!!!!!!`

**Comment by jphenow** [comment]
Which succeeded?

**Comment by jnwaletzko** [comment]
The first one. We have fancy new checks now. 💁 
image

**Comment by jerickson** [comment]
We _really_ need to fix that.  QA approval doesn't make sense at the commit level.

**Pull request merged**
